messages:
  responses:
    start: "Привет! Чтобы сохранять ссылки в своем Raindrop аккаунте, для начала тебе необходимо дать мне на это доступ. Для этого переходи по ссылке:\n%s"
    already_authorized: "Ты уже авторизовался с помощью своего Raindrop аккаунта. Присылай ссылку чтобы сохранить."
    unknown_command: "Я не знаю такой команды :("
    link_saved: "Ссылка успешно сохранена!"
  errors:
    default: "Произошла неизвестная ошибка."
    invalid_url:  "Это невалидная ссылка."
    unable_to_save: "Не удалось сохранить ссылку в Raindrop. Попробуйте пожалуйста позже."
