services:
  app:
    container_name: go_app
    build:
      context: .
      dockerfile: Dockerfile
      target: ${GO_ENV}
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - go-network
    volumes:
      - .:/app

  db:
    container_name: go_db
    image: postgres:15
    environment:
       POSTGRES_USER: ${POSTGRES_USER}
       POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
       POSTGRES_DB: ${POSTGRES_DB}
    restart: always
    ports:
      - "5433:${POSTGRES_PORT}"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
    - go-network

volumes:  
  pgdata: {}

networks:
  go-network:
    driver: bridge